### ISSUE TITLE
Хостинг

### ISSUE THREAD

**Issue by mkpankov** [suhr/rust-by-example#13]
Приветствую,

Предлагаю захостить перевод книги где-то - хотя бы на GitHub Pages. Мы бы сослались на этот перевод и привлекли бы людей к переводу оставшихся разделов.

Какие мысли на этот счёт? Потенциально могу помочь с реализацией этого.

**Comment by suhr** [comment]
Хорошая идея, но сначала надо переписать хотя бы то, что уже переведено: термины *сильно* расходятся с теми, что в rust_book_ru.

У меня пока что руки до этого не доходят, к сожалению.

**Comment by mkpankov** [comment]
Ок, понял.

Эту закрываю, буду иметь ввиду что надо обновить терминологию.
